version: "3.3"
services:
  server:
    image: flowmoco/gluster-server:v1.0.2
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.gluster.ssd == true
    networks:
      - gluster
    volumes:
      - /data/glusterfs:/data/glusterfs
      - metadata:/var/lib/glusterd
networks:
  gluster:
    external: true
volumes:
  metadata:


